### ISSUE TITLE
Pre-authorization

### ISSUE THREAD

**Issue by goodmanio** [chef/oc-id#2]
@cnunciato: Foremost, this is excellent!

Any ideas on how we’ll handle pre-authorization (e.g. [`skip_authorization`](https://github.com/opscode/oc-id/blob/master/files/default/app/config/initializers/doorkeeper.rb#L65-L70))?

**Comment by stevendanna** [comment]
This issue has been moved to https://github.com/chef/chef-server/issues/206 as part of our work to consolidate the components of chef-server into a single repository.
