### ISSUE TITLE
Don't allow "system" users to request password resets

### ISSUE THREAD

**Issue by smith** [chef/oc-id#44]
Currently this only means "pivotal." You shouldn't be able to request a password reset for pivotal, since pivotal can't authenticate with a password. Anybody who tries this should get a helpful error message.

**Comment by luckymike** [comment]
I'd also suggest setting that users's email to 'nil' or some other plainly unusable value. Seeing that email address is likely to raise sirens for some security teams, even if we "know" that it's not functionally a concern.

**Comment by stevendanna** [comment]
This issue has been moved here https://github.com/chef/chef-server/issues/198 as part of our work to consolidate the components of the Chef Server into a single repository.
