### ISSUE TITLE
Password reset web form identifies if username doesn't exist

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/oc-id#45]
It has been brought to my attention that this information could be used by a brute force method to identify valid usernames.

I think we should make our own decision about this but I think it's worth noting that many other sites do this.

I also think it's worth noting that a list of these users could be gathered much more easily by other means.

**Comment by stevendanna** [comment]
This issue was moved here: https://github.com/chef/chef-server/issues/197

Thanks!
