### ISSUE TITLE
OC-ID integration with supermarket

### ISSUE THREAD

**Issue by cmluciano** [chef/oc-id#53]
I'm having problems trying to figure out what link to hit in order to create new applications. We are using chef-server 12 and following along with https://www.chef.io/blog/2014/08/29/getting-started-with-oc-id-and-supermarket/. 

The post appears to be out of date but we did manage to get the admin line added, but my profile does not present the "create new app" button.

We're looking at moving forward with creating a large supermarket instance internally. I would love to help to update that blog post for post-chef 12 configuration once we have something up.

**Comment by nellshamrell** [comment]
Sorry you experienced this issue.  Make sure you are hitting https://your_chef_server_url/id/oauth/applications rather than https://your_chef_server_url/id/oauth/authorized_applications, as is currently the default.

**Comment by cmluciano** [comment]
Unfortunately this gives me a 404. Is there any configuration outside of adding an admin section in chef 12?

![screen shot 2015-04-11 at 2 30 55 pm](https://cloud.githubusercontent.com/assets/4790487/7102717/8704cffe-e057-11e4-9ff4-f31d7c983ba3.png)

**Comment by cmluciano** [comment]
Using /id/oauth/authorized_applications does get me a valid page with 
![screen shot 2015-04-13 at 3 28 47 pm](https://cloud.githubusercontent.com/assets/4790487/7123667/cc018480-e1f1-11e4-802b-3de0f4a77be1.png)

**Comment by cmluciano** [comment]
Should I just create one in the file as detailed here https://docs.chef.io/config_rb_server_optional_settings.html#oc-id ?

**Comment by cmluciano** [comment]
/facepalm I messed up my username in the chef-server.rb file. Thanks for your help
